# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-25 08:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0002_auto_20170917_1618'),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='slug',
            field=models.SlugField(max_length=30, null=True, unique=True),
        ),
    ]
