# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-25 09:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0004_auto_20170925_0857'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board',
            name='slug',
            field=models.SlugField(max_length=30, unique=True),
        ),
    ]
